### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#277]
We should check / add and fix any linting issues on all buildpack repos.

- use `husky`, `lint-staged`, `prettier`
- optional linter: `shellcheck`, `eslint` (depends on repo)

This is also an uber issue for all repos. 🙃 

# TODO:
- [ ] containerbase/ruby-prebuild#10
- [ ] containerbase/php-prebuild#21
- [ ] containerbase/python-prebuild#11
